# 基础镜像
FROM amazoncorretto:11.0.16
# adminor
MAINTAINER qbs

# 挂载目录
VOLUME /mydata/app
# 创建目录
RUN mkdir -p /mydata/app
# 指定路径
WORKDIR /mydata/app
# 复制jar文件到路径
COPY ./jar/train-screen.jar /mydata/app/train-screen.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","-Dspring.cloud.nacos.discovery.server-addr=${nacos_address}","-Dspring.cloud.nacos.discovery.namespace=${nacos_namespace}","-Dspring.cloud.nacos.config.server-addr=${nacos_address}","-Dspring.cloud.nacos.config.namespace=${nacos_namespace}","-Xms500m", "-Xmx1000m","train-screen.jar"]
